# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, choices=[(b'gliffy', b'Gliffy')], max_length=255, null=True)),
            ],
        ),
    ]
