# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_embed_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_submission',
            name='last_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
